### ISSUE TITLE
Error no server

### ISSUE THREAD

**Issue by inkomomutane** [inkomomutane/sumburero#2]
@jfm-dev 
**Antes de fazer fazer o pull request no server certfica no local.** 
Que tudo esta a correr como deveria. 

Passo 1: 

Rodar o comando:
 ```shell  
 npm run build
  ```
Alterar o file .env

```env 
...
APP_ENV=production
```

   ```shell  
 php artisan optimize:clear && composer du 
  ```
  
  Certficar que no local esta a rodar sem nenhum erro com enviroment de produção. 
  Quando tudo estiver correcto aí sim voce faz um pull request. 
  Porque só fazendo merge na branch `main` pode causar errors no server e não vai saber resolver. 
  
 Desfazer os merges da branch para a última funcional. => [9270d86](https://github.com/inkomomutane/sumburero/commit/9270d862d63d32bd347b67d81259241181ddff36). 
 Peço para fazer isso antes. 
 Só farei as alteração na branch main a dev continua

**Comment by jfm-dev** [comment]
Ok

**Comment by inkomomutane** [comment]
> Ok

Já fiz o reset

**Comment by inkomomutane** [comment]
Para teres a mesma versão do server na branch `main` 
```git 
git reset --hard origin/main
```

**Comment by jfm-dev** [comment]
Ok tambem estava a mexer.

mas ja esta.
